apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetracker-admin-panel
  namespace: treetracker-webapp-mvp
  labels:
    app: treetracker-admin-panel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: treetracker-admin-panel
  template:
    metadata:
      labels:
        app: treetracker-admin-panel
    spec:
      imagePullSecrets:
      - name: registry-treetracker-registry
      containers:
      - name: treetracker-admin-panel
        image: registry.digitalocean.com/treetracker-registry/treetracker-web:admin-panel
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: REACT_APP_AUTH_API_URL
          value: "http://138.68.4.47:30001/api/v1"
        - name: REACT_APP_CAPTURE_API_URL
          value: "http://138.68.4.47:30002"
        - name: REACT_APP_TOKEN_API_URL
          value: "http://138.68.4.47:30004"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
