apiVersion: v1
kind: Service
metadata:
  name: treetracker-admin-panel-service
  namespace: treetracker-webapp-mvp
  labels:
    app: treetracker-admin-panel
spec:
  type: NodePort
  selector:
    app: treetracker-admin-panel
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30010
    protocol: TCP
